# Generated by Django 2.1.3 on 2018-12-02 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import home.models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BigSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('imageResource', models.ImageField(blank=True, upload_to='image')),
            ],
            options={
                'verbose_name': 'Big Section',
                'verbose_name_plural': 'Big Sections',
                'db_table': 'Big Section collection',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('imageResource', models.ImageField(blank=True, upload_to='image')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'db_table': 'Project collection',
            },
        ),
        migrations.CreateModel(
            name='StepOneInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_interests', multiselectfield.db.fields.MultiSelectField(default=None, max_length=200, verbose_name=home.models.SubSection)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('imageResource', models.ImageField(blank=True, upload_to='image')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.BigSection')),
            ],
            options={
                'verbose_name': 'Sub Section',
                'verbose_name_plural': 'Sub Sections',
                'db_table': 'Sub Section collection',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.SubSection'),
        ),
    ]
