# Generated by Django 2.1.3 on 2018-12-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='steponeinterest',
            name='user_interests',
        ),
        migrations.AddField(
            model_name='steponeinterest',
            name='user_interests',
            field=models.ManyToManyField(default=None, to='home.SubSection'),
        ),
    ]
