# Generated by Django 2.1.3 on 2018-12-10 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20181203_1109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subsection',
            old_name='imageResource',
            new_name='steponeimage',
        ),
    ]
