# Generated by Django 2.1.1 on 2018-10-22 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0005_stageoneinterests'),
    ]

    operations = [
        migrations.CreateModel(
            name='StageOneInterestsPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_interests', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.StageOneInterests')),
            ],
        ),
    ]
