# Generated by Django 2.1.1 on 2018-10-22 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_stageoneinterestspost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stageoneinterestspost',
            name='user_interests',
        ),
        migrations.AddField(
            model_name='stageoneinterestspost',
            name='user_interests',
            field=models.ManyToManyField(to='home.StageOneInterests'),
        ),
    ]
