# Generated by Django 2.1.1 on 2018-10-22 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20181022_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='stageoneinterestspost',
            name='other_interests',
            field=models.TextField(default='love'),
        ),
    ]
