# Generated by Django 2.1.3 on 2019-04-21 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='position',
        ),
    ]
