# Generated by Django 2.1.1 on 2018-10-22 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_stageoneinterestspost_other_interests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stageoneinterestspost',
            name='other_interests',
            field=models.TextField(blank=True),
        ),
    ]
