# Generated by Django 2.1.1 on 2018-10-24 08:21

from django.db import migrations
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20181022_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stageoneinterestspost',
            name='user_interests',
            field=mptt.fields.TreeManyToManyField(to='home.StageOneInterests'),
        ),
    ]
