# Generated by Django 2.1.3 on 2019-05-05 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_team_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='position',
        ),
    ]
