# Generated by Django 2.1.1 on 2018-10-24 11:45

from django.db import migrations
import home.models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20181024_0821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stageoneinterestspost',
            name='user_interests',
        ),
        migrations.AddField(
            model_name='stageoneinterestspost',
            name='user_interests',
            field=multiselectfield.db.fields.MultiSelectField(default=0, max_length=200, verbose_name=home.models.StageOneInterests),
        ),
    ]
