# Generated by Django 2.1.3 on 2019-05-05 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_team_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='title',
            field=models.CharField(default='title_default', max_length=50),
        ),
    ]
