# Generated by Django 2.1.1 on 2018-10-24 12:02

from django.db import migrations
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20181024_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stageoneinterestspost',
            name='user_interests',
        ),
        migrations.AddField(
            model_name='stageoneinterestspost',
            name='user_interests',
            field=mptt.fields.TreeManyToManyField(to='home.StageOneInterests'),
        ),
    ]
