# Generated by Django 2.1.3 on 2019-05-07 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20190421_1129'),
        ('home', '0012_team_title'),
    ]

    operations = [
    ]
