# Generated by Django 2.1.1 on 2018-10-24 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20181024_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stageoneinterestspost',
            name='user_interests',
            field=models.ManyToManyField(to='home.StageOneInterests'),
        ),
    ]
