# Generated by Django 2.1.3 on 2019-09-09 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20190909_0846'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='steponeinterest',
            options={'ordering': ['created', 'user'], 'verbose_name': 'Step One', 'verbose_name_plural': 'Step One Interests of User'},
        ),
        migrations.AlterModelTable(
            name='steponeinterest',
            table='Step One Interest of User',
        ),
    ]
