# Generated by Django 2.1.3 on 2018-11-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20181107_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stageoneinterestspost',
            name='other_interests',
        ),
        migrations.AddField(
            model_name='stageoneinterests',
            name='image',
            field=models.ImageField(blank=True, upload_to='image'),
        ),
    ]
