# Generated by Django 2.1.3 on 2018-11-26 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20181126_1048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stageoneinterests',
            old_name='image',
            new_name='imageResource',
        ),
    ]
