# Generated by Django 2.1.3 on 2019-12-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20190909_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='SMARTgoals',
            field=models.TextField(blank=True, null=True, verbose_name='SMART goals'),
        ),
    ]
