# Generated by Django 2.1.3 on 2019-12-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20191201_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='taskDue',
            field=models.DateField(blank=True, null=True, verbose_name='duedate for each tasks'),
        ),
    ]
