# Generated by Django 2.1.3 on 2019-12-02 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20191202_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tasks',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='tasks'),
        ),
    ]
