# Generated by Django 2.1.3 on 2019-12-03 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20191202_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(blank=True, max_length=500, null=True, verbose_name='tasks')),
                ('due', models.DateField(blank=True, null=True, verbose_name='duedate')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Project')),
            ],
            options={
                'verbose_name': 'project task',
            },
        ),
    ]
